<?php


/**
 * Implements hook_theme().
 */

function specbee_theme() {
    return [
      'specbee_date_time_block' => [
        'variables' => ['data' => NULL],
        'template' => 'block--specbee-time-date-block',
      ],
    ];
  }
  
/**
 * Implements hook_preprocess_block().
 */

// function specbee_preprocess_block(&$variables) {
//   if($variables['plugin_id'] == 'Specbee_Time_Date_block'){
//     $cdate = \Drupal::service('specbee.date_time_custom_services')->getDate();
//     $variables['content']['#data']['Date'] = $cdate;
//     $variables['elements']['content']['#data']['Date'] = $cdate;
//     dpm($variables);
//   }
// }
